#!/usr/bin/expect

set tool "clic"
set timeout 1
set CLIC "./clic "
set srcdir .
set objdir .

set testdata {
    {"1+2"              "3.000000"}
    {" "                "---syntax error"}
    {"1 2 3 4"          "1234.000000"}
    {"1.0 * 3"          "3.000000"}
    {"2 - 4"            "-2.000000"}
    {"a * bc"           "---unknown identifier"}
    {"2^3"              "8.000000"}
    {"2 +- 3"           "-1.000000"}
    {"2/0"              "inf"}
    {"\\c"              ""}
    {"\\v"              "e = 2.718282 (readonly)\nPI = 3.141593 (readonly)\n"}
    {"\\f"              "\\+\n-\n\\*\n/\n\^\n\(\n\)\nneg\nnul\nsin\ncos\ntg\narcsin\narccos\narctg\nexp\nln\nlg\nsqrt\ncbrt\nsh\nch\nth\nerf\nerfc\nG\n"}
    {"\\h"              "\\v - variable list\n\\f - function list\n\q - quit\n"}
    {"\\k"              "---unknown command"}
    {"=="               "---more than one '='"}
    {"x=2"              "2.000000"}
    {"var = 22"         "---invalid variable or function name"}
    {"reallyreallyreallyreallylooooooooooooooooooooooooooooooooooooooooooooooooongvariablename = 16"    "---identifier is too long"}
    {"x=3"              "3.000000"}
    {"y=(x^2)"          "9.000000"}
    {"cos(PI)"          "-1.000000"}
    {"sin 1"            "---unknown identifier"}
    {"arcsin (PI/2"     "---syntax error"}
    {"arccos (PI/2)"    "nan"}
    {"tg (1)"           "1.557408"}
    {"arctg(60)"        "1.554131"}
    {"exp(e)"           "15.154262"}
    {"e"                "2.718282"}
    {"ln(e)"            "1.000000"}
    {"lg(64)"           "1.806180"}
    {"sqrt()"           "---syntax error"}
    {"sqrt(100)"        "10.000000"}
    {"cbrt(27)"         "3.000000"}
    {"sh(1)"            "1.175201"}
    {"ch(400)"          "261073484488207212735209064459146536185571409342468633391734682619453983450537172529370150955738199057031807490658452264097559473569286551524628636325192189907944179352207360.000000"}
    {"th(-4)"           "-0.999329"}
    {"erf(3)"           "0.999978"}
    {"erfc(e)"          "0.000121"}
    {"G(0)"             "inf"}
    {"e=12345"          "---you can not change the value"}
    {"34=16"            "---invalid variable or function name"}
    {"(3-9*4+(4/2))"    "-31.000000"}
    {"sqrt(-4)"         "nan"}
    {"9999999999999999" "9999999999999999.000000"}
    {"99999999999999999999999999999"    "99999999999999999999999999999.000000"}
    {"8^0"              "1.000000"}
    {"0^1"              "0.000000"}
    {"0^0"              "1.000000"}
    {"0/9"              "0.000000"}
    {"3/3"              "1.000000"}
    {"z4=23"            "23.000000"}
    {"x=e"              "2.718282"}
    {"u=3^2^3"          "6561.000000"}
    {"v=14"             "---no more space left for variables"}
    {"x=3"              "3.000000"}
    {"Ü"                "---unknown identifier"}
}


global CLIC

eval "spawn $CLIC";

foreach pattern $testdata {
    set inputs [lindex $pattern 0]
    expect "clic2>" {send "$inputs\n"}
    expect {
        -re [lindex $pattern 1] {
            pass $inputs
        }
        timeout { fail $inputs }
        default { fail $inputs }
    }
}

expect "clic2>" {send "\\q\r"}

expect eof
